language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get install python-webkit
# command to install dependencies
install:
  - pip install -r requirements.txt --use-mirrors
# command to run tests
script: python setup.py bdist_egg
